### ISSUE TITLE
ABP/OTAA support

### ISSUE THREAD

**Issue by aparcar** [lemariva/uPyLoRaWAN#1]
Hi, maybe this question is entirely wrong here, but I'd like to use this framework in combination with [TTN](https://www.thethingsnetwork.org/), which requires ABP/OTAA authentication for devices. I have only seen such implementations from [PyCom](https://docs.pycom.io/tutorials/lora/lorawan-otaa.html), can you estimate the effort to support this as well?

**Comment by lemariva** [comment]
Hi, I think it is possible, but I need to read more about ABP/OTAA authentications. Nowadays I don't have enough time, but it is in my ToDo list.

**Comment by DanielBustillos** [comment]
Hi, was this developed? I havent found any reference in the code. Tks.
