### ISSUE TITLE
TTGO ESP LoRa32 with Lopy receiver

### ISSUE THREAD

**Issue by DuaneKaufman** [lemariva/uPyLoRaWAN#17]
Hi,
I am trying to use the 'sender' example on my TTGO ESP LoRa32 (V 1) board with a LoPy as a receiver (actually running as a nanogateway from the examples)

I am not getting any packets through - nothing. I am running Micropython 1.14 on the TTGO, with uPyLoRaWAN.

When booting the TTGO, I see the following:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5008
ho 0 tail 12 room 4
load:0x40078000,len:10600
ho 0 tail 12 room 4
load:0x40080400,len:5684
entry 0x400806bc
Warning: SPI(-1, ...) is deprecated, use SoftSPI(...) instead
SX version: 18
example = sender
LoRa Sender
Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead

Are thee warnings meaningful? If not, are there any ideas how to further trouble-shoot?

Sincerely,
Duane Kaufman
[TTGO_sender.zip](https://github.com/lemariva/uPyLoRaWAN/files/5974067/TTGO_sender.zip)
[LoPy_Receiver.zip](https://github.com/lemariva/uPyLoRaWAN/files/5974070/LoPy_Receiver.zip)

**Comment by lemariva** [comment]
You can replace the lines:
```
from machine import Pin, SPI
device_spi = SPI(baudrate = 10000000,  [...]
```
with 
```
from machine import Pin, SoftSPI
device_spi = SoftSPI(baudrate = 10000000,  [...]
```
To solve the warnings. Same with the I2C. I'll be upgrading the repository soon.
