### ISSUE TITLE
Compatibility with 433 MHz

### ISSUE THREAD

**Issue by abdylan** [lemariva/uPyLoRaWAN#2]
Hi,

Im using the Heltec ESP32 LoRa Dev kit (in Pakistan) and i was wondering whether this package is compatible with 433 MHz as well.

So far i havent gotten any results and my conclusions are:

1.  Faulty LoRa module in either of the 2 ESP32s
2. uPyLoRa compatibilty issue with 433 MHz

**Comment by lemariva** [comment]
Sorry for the late response. It should also work with 433MHz, but you need to change some settings in the file: sx127x.py or you need to initialize the object with the correct configuration (eg. 'frequency': 433E6). Check also the PINs, they vary between LoRa Dev kits.
