### ISSUE TITLE
Bug in sx127x.py?

### ISSUE THREAD

**Issue by frankvanhooft** [lemariva/uPyLoRaWAN#3]
I'm wondering if there's a bug in the file sx127x.py; I thought I'd ask here before going any further.

The function:

def aquire_lock(self, lock = False):
        self._lock = False

Shouldn't this be instead:

def aquire_lock(self, lock = False):
        self._lock = lock

Thanks.

**Comment by rocket-pig** [comment]
Please fork or PR and make your revisions public! I for one would greatly appreciate that. 

( Im not connected to original author.  These boards are in the mail and I'm looking forward to working on them.  )

**Comment by lemariva** [comment]
I've some time today and I cleaned the code.
