### ISSUE TITLE
LoRaWAN OTAA and ABP?

### ISSUE THREAD

**Issue by beyonlo** [lemariva/uPyLoRaWAN#4]
Hi, this driver works with the LoRaWAN using the OTAA and ABP activation?

I need to use my ESP32 device with LoRa using a LoRa provider (LoraWAN), is possible?

Thank you.

**Comment by lemariva** [comment]
The [new branch](https://github.com/lemariva/uPyLora/tree/LoRaWAN) supports LoRaWAN using the ABP activation method.
