### ISSUE TITLE
LORA_RST on pin 14

### ISSUE THREAD

**Issue by aparcar** [lemariva/uPyLoRaWAN#5]
https://github.com/lemariva/uPyLoRaWAN/blob/f3f068727eba1526c8436a5a022b9abaea0d3181/main.py#L19

Following this picture you're using the wrong pin for LORA_RST. It should be pin 14.

![image](https://user-images.githubusercontent.com/16000931/76691054-a698b600-65ea-11ea-9a5f-0668040f875a.png)

**Comment by lemariva** [comment]
closed with eebd391ba822190695efe3c6308bef43d711fdeb
